# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs: 
      test_workflow:
        required: true
        default: "false"
        type: choice
        options:
          - "false"
          - "true"
        

jobs:

  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.test_workflow == 'true'
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        cache: true
        cache-dependency-path: application-code/go.sum

    - name: Download Dependency
      working-directory: application-code
      run: go mod download

    - name: Test
      working-directory: application-code
      run: |
        go test -v ./... -r || "review manually"
        INTEGRATION=true go test -v --tags=integration ./...


    - name: Code Quality
      uses: dmux/go-quality-gate-action@v1.0.0
      with:
         working-directory: application-code 

    - name: Vulnerabity Scan
      working-directory: application-code 
      run: |
        go install golang.org/x/vuln/cmd/govulncheck@latest
        govulncheck./... || echo "Vulnerability detected"
    
    
